services:
  - type: web
    name: my-python-service
    runtime: python
    env: python
    plan: standard
    region: oregon # Choose the region closest to your users
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000

